version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing dependency...
      - pwd
      - node -v
      - npm -v
      - yarn -v
  pre_build:
    commands:
      - printenv > .env
  build:
    commands:
      - echo Build started on `date`
      - yarn install --frozen-lockfile
      - NODE_ENV=production yarn build
  post_build:
    commands:
      - echo Entered the post_build phase...
      - rm -rf **/node_modules
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
